# Generated by Django 3.2.6 on 2024-02-12 01:43

from django.db import migrations, models
import django.db.models.deletion
import pay.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refno', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=pay.models.filepath)),
                ('parent', models.ForeignKey(db_column='parent', on_delete=django.db.models.deletion.DO_NOTHING, to='home.parent')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='home.student')),
            ],
        ),
    ]
