# Generated by Django 3.2.6 on 2024-02-12 01:44

from django.db import migrations, models
import django.db.models.deletion
import pay.models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentor',
            fields=[
                ('orno', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=pay.models.orpath)),
                ('paymentdate', models.CharField(blank=True, max_length=50, null=True)),
                ('payment', models.ForeignKey(blank=True, db_column='payment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pay.payment')),
            ],
        ),
    ]
