# Generated by Django 3.2.6 on 2024-02-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_paymentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
