# Generated by Django 4.2.10 on 2024-02-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
