# Generated by Django 4.2.10 on 2024-03-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_entrymonitoring_clockin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymonitoring',
            name='clockin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entrymonitoring',
            name='clockout',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
