# Generated by Django 4.2.10 on 2024-04-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_entrymonitoring_clockin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'managed': True, 'ordering': ('-id',)},
        ),
    ]
