# Generated by Django 4.2.10 on 2024-04-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_parent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='parent',
            name='dateregistered',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
