# Generated by Django 3.2.6 on 2024-02-16 05:31

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('venue', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=event.models.eventpath)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('attendees', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
    ]
