# Generated by Django 4.2.10 on 2024-03-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreregSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField(blank=True, max_length=45, null=True)),
                ('date_close', models.DateTimeField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'prereg_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WebAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField(blank=True, max_length=45, null=True)),
                ('date_close', models.DateTimeField(blank=True, max_length=45, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'webapp_settings',
                'managed': True,
            },
        ),
    ]
